application: sf-cs253
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /
  script: cs253.app

- url: /unit1/hello
  script: hello-udacity.app

- url: /unit1/hello/.*
  script: hello-udacity.app

- url: /unit2/rot13
  script: ROT13.app

- url: /unit2/rot13/.*
  script: ROT13.app

- url: /unit2/signup
  script: signup.app

- url: /unit2/signup/.*
  script: signup.app

- url: /unit3/basicblog
  script: basicblog.app

- url: /unit3/basicblog/.*
  script: basicblog.app

- url: /.*
  script: cs253.app
